
[tasks.debug_musl]
description = "Build with wasm-pack in release mode"
env = { "PKG_CONFIG_ALLOW_CROSS" = "1", "OPENSSL_STATIC" = "true", "OPENSSL_DIR" = "/musl" }
command = "cargo"
args = ["build", "--target", "x86_64-unknown-linux-musl"]

[tasks.musl]
description = "Build with wasm-pack in release mode"
env = { "PKG_CONFIG_ALLOW_CROSS" = "1", "OPENSSL_STATIC" = "true", "OPENSSL_DIR" = "/musl" }
command = "cargo"
args = ["build", "--target", "x86_64-unknown-linux-musl", "--release"]